include("Utils")
include("ExternalsUtils")

block()
    set(LIB_NAME "glm")
    announce("Configuring \"${LIB_NAME}\" external library.")

    force_bool(GLM_BUILD_TESTS OFF)
    force_bool(GLM_BUILD_INSTALL OFF)
    force_bool(BUILD_SHARED_LIBS OFF)
    force_bool(GLM_ENABLE_CXX_98 OFF)
    force_bool(GLM_ENABLE_CXX_11 OFF)
    force_bool(GLM_ENABLE_CXX_14 OFF)
    force_bool(GLM_ENABLE_CXX_17 OFF)
    force_bool(GLM_ENABLE_CXX_20 ON)
    force_bool(GLM_ENABLE_LANG_EXTENSIONS OFF)
    force_bool(GLM_DISABLE_AUTO_DETECTION OFF)
    force_bool(GLM_ENABLE_FAST_MATH OFF)
    
    if(NOT EMSCRIPTEN)
        force_bool(GLM_ENABLE_SIMD_SSE2 ON)
        force_bool(GLM_ENABLE_SIMD_SSE3 ON)
        force_bool(GLM_ENABLE_SIMD_SSSE3 ON)
        force_bool(GLM_ENABLE_SIMD_SSE4_1 ON)
        force_bool(GLM_ENABLE_SIMD_SSE4_2 ON)
        force_bool(GLM_ENABLE_SIMD_AVX ON)
        force_bool(GLM_ENABLE_SIMD_AVX2 ON)
        force_bool(GLM_ENABLE_SIMD_NEON ON)
    endif ()
    
    force_bool(GLM_FORCE_PURE OFF)

    add_external_subdirectory(${LIB_NAME})
endblock()