include("Utils")
include("ExternalsUtils")

block()
    set(lib_name "glm")
    Announce("Configuring \"${lib_name}\" external library.")

    ForceBool(GLM_BUILD_TESTS OFF)
    ForceBool(GLM_BUILD_INSTALL OFF)
    ForceBool(BUILD_SHARED_LIBS OFF)
    ForceBool(GLM_ENABLE_CXX_98 OFF)
    ForceBool(GLM_ENABLE_CXX_11 OFF)
    ForceBool(GLM_ENABLE_CXX_14 OFF)
    ForceBool(GLM_ENABLE_CXX_17 OFF)
    ForceBool(GLM_ENABLE_CXX_20 ON)
    ForceBool(GLM_ENABLE_LANG_EXTENSIONS OFF)
    ForceBool(GLM_DISABLE_AUTO_DETECTION OFF)
    ForceBool(GLM_ENABLE_FAST_MATH OFF)
    
    if(NOT EMSCRIPTEN)
        ForceBool(GLM_ENABLE_SIMD_SSE2 ON)
        ForceBool(GLM_ENABLE_SIMD_SSE3 ON)
        ForceBool(GLM_ENABLE_SIMD_SSSE3 ON)
        ForceBool(GLM_ENABLE_SIMD_SSE4_1 ON)
        ForceBool(GLM_ENABLE_SIMD_SSE4_2 ON)
        ForceBool(GLM_ENABLE_SIMD_AVX ON)
        ForceBool(GLM_ENABLE_SIMD_AVX2 ON)
        ForceBool(GLM_ENABLE_SIMD_NEON ON)
    endif ()
    
    ForceBool(GLM_FORCE_PURE OFF)

    AddExternalSubdirectory(${lib_name})
endblock()