# ========== Global configuration ===========

# Default C++ standard
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

# Set "Edit and continue" for MSVC debug builds, this is required by "Blink" hot reloading
#cmake_policy(SET CMP0141 NEW) # required
#set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "$<$<CONFIG:Debug,RelWithDebInfo>:EditAndContinue>")
string(REGEX REPLACE "/Zi" "/ZI" CMAKE_C_FLAGS   "${CMAKE_C_FLAGS}")
string(REGEX REPLACE "/Zi" "/ZI" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
string(REGEX REPLACE "/Zi" "/ZI" CMAKE_C_FLAGS_DEBUG   "${CMAKE_C_FLAGS_DEBUG}")
string(REGEX REPLACE "/Zi" "/ZI" CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}")
string(REGEX REPLACE "/Zi" "/ZI" CMAKE_C_FLAGS_DEBUG_INIT   "${CMAKE_C_FLAGS_DEBUG_INIT}")
string(REGEX REPLACE "/Zi" "/ZI" CMAKE_CXX_FLAGS_DEBUG_INIT "${CMAKE_CXX_FLAGS_DEBUG_INIT}")
string(REGEX REPLACE "/Zi" "/ZI" CMAKE_C_FLAGS_RELWITHDEBINFO   "${CMAKE_C_FLAGS_RELWITHDEBINFO}")
string(REGEX REPLACE "/Zi" "/ZI" CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
string(REGEX REPLACE "/Zi" "/ZI" CMAKE_C_FLAGS_RELWITHDEBINFO_INIT   "${CMAKE_C_FLAGS_RELWITHDEBINFO_INIT}")
string(REGEX REPLACE "/Zi" "/ZI" CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "${CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT}")

